# Generated by Django 4.0 on 2021-12-17 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_remove_product_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='year',
            field=models.IntegerField(blank=True, default=2020, null=True, verbose_name='Год создания'),
        ),
    ]
